version: "2"

services:
  mysql:
    container_name: mysql
    image: mysql:5.5.60
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    restart: always



